FROM python:3.9-slim

WORKDIR /home/code
COPY . .
#RUN python -m pip install --upgrade pip
#RUN ["pip","install","-r","/home/code/requirements.txt"]
RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -r /home/code/requirements.txt

